dtolnay/semver

README.md

Mismatched types were cause of the following error when try to compile the example code:
```
error: mismatched types: expected `u64`, found `usize` (expected u64, found usize)
```
The issue pretty much resembles rust-lang/rust#20967 in rust-lang/rust#20895.

Fix compilation error of readme example

---

src/lib.rs
src/version.rs

I had a quick look through the spec, and could not find any information on if build metadata and pre-release information should be wiped when incrementing versions. Because of that, I have left them untouched; I'll have another look when I get home from work, and fix it if I am in error.
If you don't want to support mutable Versions, let me know, and I'll re-implement this in a suitable manner. 
Thanks in advance :)

Introduce the ability to increment mutable Versions

---

Cargo.toml
src/version.rs

Had an issue in which I couldn't up-cast semver's `ParseError` to `Box<Error>`. Didn't see PR #41 when I wrote this (oops!). Unlike the other PR, this patch doesn't restructure `ParseError` at all.

Implement Error for ParseError

---

src/version.rs

This is just a utility that checks the prerelease data to see if the current version is a prerelease version
Alternative forms if wording is wrong: is_stable() that only returns self.pre.is_empty() without inversion, or is_unstable()

Version: Add is_prerelease() -> bool

---

src/version.rs
src/version_req.rs

This fixes #53 by implementing the rules specified at https://docs.npmjs.com/misc/semver#prerelease-tags
r? @steveklabnik

Implement comparison for pre-release tags.

---

src/lib.rs
src/version_req.rs

This is an implementation of PR #57 (tracked in PR #58).

Version range sets

---

src/lib.rs
src/parser.rs

- Used `assert_eq!` instead of `assert!` in some places for better reporting
- Improved the word parser combinator to always require 1-or-more characters
- Added error messages (switch from `GenericError` to `ParseError(String)`)
- Make it return an `Err` result if there's unparsed input
- Enable two commented-out tests to test the previous item

Nom parser improvements

---

src/parser.rs

A bit of nitpicking here, but it removes an `unwrap()` :)
I could simplify the `identifiers` function as well, but I run into some type inference issues right now.

Simplify some parsers

---

src/lib.rs
src/version.rs
src/version_req.rs

This branch does several things, all aimed at passing Cargo's test suite again:
* reverts #60, and #54, which broke said suites. These features are both desired, but since we haven't released them yet, I'd like to mitigate breakage before reintroducing.
* re-opens #57 and #53, the tracking issues for those features
* Implements `Display`/`Error` for SemverError
* Closes #61, which is trying to mitigate #60's breakage.
I plan on following this up with a way to test against Cargo in CI.

Reduce regressions

---

src/version_req.rs

With this extra conditional, a pre-release version of 0 gets parsed as an
AlphaNumeric rather than a Numeric.
Fixes #73 
@wycats do you have any idea why this conditional was included here?

Fix bug with pre-release parsing

---

src/lib.rs
src/version.rs

This appears to have been missed in 5b7a7f8.

Export SemVerError in the public interface

---

src/version_req.rs

Once this PR succeeds in CI, #88 can be considered fixed.
Will have a look at the `semver_parser` crate next.

Add test to assert for issue 88

---

src/version_req.rs
tests/deprecation.rs

Due to issues like https://github.com/rust-lang/cargo/issues/3124, we've
found that the old parser was lenient in ways that the new parser isn't.
We've analyzed all the crates on crates.io, and found the patterns that
weren't working.
This commit adds support back for those versions, but marks them as
deprecated. Each of them had a different way in which they were
incorrect, but resolved to some kind of correct constraint. So the
deprecation strategy is this:
1. If a version fails to parse, check if it matches the deprecated
pattern.
2. If it does, convert it to the real pattern.
3. Return an error that it's deprecated, and the error will contain the
fixed-up version constraint.

Parse deprecated versions.

---

README.md

I'm not sure if the older version in the README.md was deliberate or not. :-)
(I'm using `semver` in Faraday's soon-to-be-announced [cage](https://github.com/faradayio/cage) tool, to [make sure that cage projects are compatible](https://github.com/faradayio/cage/commit/c970a0091adbdca64562d19fceebf81787218ee2#diff-bd5f449c6715bc3eda4d168fdaebf52eR11) with the installed version of cage. Very nicely designed!)

README.md: Update version in Cargo.toml example

---

src/version_req.rs

We improperly assumed that if we had a wildcard patch version, we must
have a non-wildcard minor version. This is actually incorrect.

Bugfix for rust-lang/cargo#3202

---

Cargo.toml
src/lib.rs
src/version.rs

The `serde_support` feature will now add the serde dependency, and allow for versions to be serialized and deserialized. I would have just called it `serde`, but you can't have an overlap of feature and dependency names.
This comes out of a personal problem I was having - since you can't define the implementation of an external trait on an external struct, I had to define the implementation manually, which is both long and boilerplate-y. This should keep the crate size down and allow for serialization as necessary.

Added serde optional support to version numbers

---

Cargo.toml
src/lib.rs
src/version.rs
tests/serde.rs

I changed the representation so that this struct:
```rust
#[derive(Serialize, Deserialize)]
struct Package {
name: String,
vers: semver::Version,
}
```
is represented as:
```json
{"name":"serde","vers":"1.0.0"}
```
Fixes #102.

Update to Serde 1.0

---

src/version_req.rs

Looks like `^` is assumed by default. To learn this, I had to read [the test](https://github.com/matklad/semver/blob/a948b9cb591f83a9b85d74296c619bb91915c915/src/version_req.rs#L552), putting it in the docstring will make it more obvious.

One more example for VersionReq::parse

---

src/version_req.rs
tests/serde.rs

Nothing fancy - just copied heavily from the equivalent for `Version`.
Should solve #119

Serialize and deserialize `VersionReq`

---

Cargo.toml
src/version.rs

Hi,
perhaps in many cases it is not necessary to parse strings to instantiate a `Version`. So I added a very simple constructor. This Message already has more characters then the diff of my PR 😀 
have a nice Sunday

Added simple constructor

---

src/lib.rs

recommit based on discussion in #140

libz blitz: add html root url attribute to crate root

---

src/lib.rs

Libz blitz/use question mark instead of unwrap in examples

---

.travis.yml
Cargo.toml
src/diesel_impls.rs
src/lib.rs
src/version.rs
src/version_req.rs
tests/diesel.rs

This code targets Diesel 1.1. I can support Diesel 1.0 if it's required,
but it will require a lot more code. Impls like this are the main focus
of 1.1.
While it'd be great if we could just have a diesel-semver crate, Rust
today requires that this be either in Diesel or Semver.
This makes the same assumptions as the serde implementations. We assume
that the values are being stored as a string, and getting them in/out is
just `FromStr` and `Display`.
I've opted to only support `Version` and `VersionReq` in this case.
Though the serde implementation supports `Identifier`, there's not an
obvious database agnostic way to store that type, and I don't think it's
nearly as commonly used as the other two.
Given that this crate supports Serde, I think it makes just as much
sense to add minimal …

Add Diesel support

---

src/version.rs
src/version_req.rs

`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon.
This PR:
- Removes the implementation of `description` 
Related PR: https://github.com/rust-lang/rust/pull/66919

Remove deprecated Error::description

---

src/lib.rs
src/version_req.rs

I can't find precedent for putting spaces in version requirements anywhere else on the web, so this seems like a wild thing to do by default. Both node-semver and https://docs.racket-lang.org/semver/index.html have their version requirements shown without spaces.

remove whitespace from Display impl of VersionReq

---

src/version_req.rs

I have some logic where it would be useful to shortcut some behaviour if
a `VersionReq` could only be matched by exactly one value. This would
help me not end up re-parsing the semver string myself to guess whether
it's a single fully-qualified exact match.

Add `VersionReq::is_exact`

---

README.md

https://www.npmjs.com/doc/misc/semver.html is a 404. The Internet
Archive does not have it so I can only take a guess at what was hosted
at this address. Taking a guess at https://www.npmjs.com/package/semver.

Fix npmjs link

---

Cargo.toml

"parsing" category is for tools for building parsers, not parsers of particular formats.

Correct crate category

---

src/lib.rs

Running `cargo doc` with a recent nightly version results in these warnings:
warning: `[parse]` cannot be resolved, ignoring it...
--> src/lib.rs:44:24
|
44 | //! objects using the [`parse`] method:
|                        ^^^^^^^ cannot be resolved, ignoring
|
= note: #[warn(intra_doc_link_resolution_failure)] on by default
= help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`
warning: `[parse]` cannot be resolved, ignoring it...
--> src/lib.rs:45:6
|
45 | //! [`parse`]: struct.Version.html#method.parse
|      ^^^^^^^ cannot be resolved, ignoring
|
= help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`
The link target needs to go in a separate paragraph, so we need a blank line before it, and doing so fixes the warning for me.

Add blank line to fix doc link resolution.

---

Cargo.toml
src/lib.rs
src/version.rs
src/version_req.rs
tests/deprecation.rs

This combines the changes from [mikrostew/semver@new-parser](https://github.com/mikrostew/semver/tree/new-parser) and the current master branch which makes it compatible with `semver-parser` `0.10.0` that hasn't quite been released. In order for the tests pass, it patches the `semver-parser` dependency to use GitHub.
Tracking Items Left:

semver-parser 0.10.0

---

tests/test_version.rs
tests/test_version_req.rs

The first commit adds some tests related to #217, that regressed in 0.12. The tests now pass on 1.0.0.
The second commit adds a test for a new parse error. I haven't checked yet if we have any legacy versions on crates.io that violate this, but the error is to spec.

Add a few tests

---

src/eval.rs
tests/test_version_req.rs

This sidesteps some mystery about what `=I.J` means in the case of prerelease versions. https://github.com/semver/semver/pull/584#pullrequestreview-671766773

Fix <I.J to not match I.J.0 prereleases

---

src/parse.rs
tests/test_version_req.rs

For example `0.4.x` is supposed to mean the same thing as `0.4.*`. https://github.com/Arnavion/derive-error-chain/blob/ed2fafa0354b10df889cf46042651a91a02d58bf/derive-error-chain/Cargo.toml#L17

Parse x and X as wildcard

---

src/display.rs
src/error.rs

The previous implementation would produce wrong unintentional output when formatting with alignment or padding, such as {:<15}.
```console
0              .1              .0               
```

Avoid inheriting formatter flags in some Display impls

---

src/lib.rs

Previously it would take you to the `#[derive(Default)] struct VersionReq`, where you had to intuit what `VersionReq { comparators: <Vec<Comparator>>::default() }` means. Now it should take you to the handwritten `impl Default for VersionReq` which shows the return value is equivalent to `VersionReq::STAR`.

Make the [src] link on impl Default for VersionReq more comprehensible

---

src/error.rs
src/parse.rs
tests/test_version_req.rs

Addresses https://github.com/dtolnay/semver/pull/266#discussion_r799848870. Closes #253.
@jonhoo I gave it the same error message for `0.20.0-any, *` as for `*, 0.20.0-any` in the earlier PR.

Improve error on wildcard after another comparator

---

.github/workflows/ci.yml
build.rs
src/backport.rs
src/identifier.rs

This lets us pass Miri's raw pointer tagging.

Eliminate ptr->int->ptr casting from Identifier implementation

---

.github/workflows/ci.yml

This speeds up the miri job in CI by 1m 37s. Previously it used to compile xargo from source on first run of `cargo miri test`.
```console
Running `"/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "install" "xargo"` to install a recent enough xargo.
Updating crates.io index
Downloading crates ...
Downloaded xargo v0.3.26
Installing xargo v0.3.26
.....
Finished release [optimized] target(s) in 1m 37s
Installing /home/runner/.cargo/bin/xargo
Installing /home/runner/.cargo/bin/xargo-check
Installed package `xargo v0.3.26` (executables `xargo`, `xargo-check`)
```

Install precompiled xargo to speed up miri job

---

src/backport.rs

I forgot `std::alloc` stabilized many versions before `extern crate alloc`.

Can use alloc from std::alloc even if there is no alloc crate

---

src/identifier.rs

See https://github.com/rust-lang/rust/issues/101899. https://github.com/rust-lang/rust/pull/95295, which looks like it is going to be un-reverted, makes the following change to the error condition of `Layout::from_size_align` and thus the safety requirement of `Layout::from_size_align_unchecked`:
```diff
/// * `size`, when rounded up to the nearest multiple of `align`,
-    ///    must not overflow (i.e., the rounded value must be less than
-    ///    or equal to `usize::MAX`).
+    ///    must not overflow isize (i.e., the rounded value must be
+    ///    less than or equal to `isize::MAX`).
```

Check for isize overflow before Layout construction

---

Cargo.toml
src/lib.rs

https://github.com/rust-lang/rust/issues/97933 has been fixed in rustdoc, so this PR undoes #286 and #281.

Remove workaround for rustdoc displaying private fields

---

src/error.rs
src/parse.rs
tests/test_version.rs

See https://github.com/Homebrew/homebrew-core/pull/114382#issuecomment-1297979948.

Add a dedicated error for parsing Version from an empty string

---

tests/test_identifier.rs
tests/test_version.rs
tests/test_version_req.rs
tests/util/mod.rs

Hi,
Thanks for your time & patience to review this PR.
We are researchers focusing on Rust unit tests. By examine the existing code, we found following unit tests can be added to improve the repo's overall unit test coverage.
We only manually changed our assert statements to make it consistent with existing macros and move the error tests to its correct location.
As for the unit tests, we found the `from_str` method for Comparator & Prerelease struct are rarely tested and there are many corner error cases in Version/VersionSeq are missed.
If you have any questions, comments or feedback, please let us know.
Thanks!

Adding missed unit test cases

---

Cargo.toml
build.rs
src/error.rs
src/lib.rs

As of recently, docs.rs defines a `docsrs` configuration for all builds, so we no longer need to do it using our own `package.metadata.docs.rs.rustdoc-args`.

Rely on docs.rs to define --cfg=docsrs by default

---

src/identifier.rs
src/impls.rs

I have [a tool](https://github.com/Eh2406/pubgrub-crates-benchmark) for benchmarking Cargoes resolver and a new PubGrub based resolver. Both resolvers spend a lot of time  checking whether two `Versions`  are equal using `Ord`. For example, `.contains` on a `BTreeMap<Versions, ...`. @arielb1 pointed out that adding a fast path makes a big  difference in the runtime of the resolvers. On master the program reports `PubGrub CPU time: 86.97min, Cargo CPU time: 190.67min`, with this PR `PubGrub CPU time: 71.33min, Cargo CPU time: 167.92min`. (For posterity the command is `cargo r -r -- -t 100` running commit `9dc991f94c45688a6d2d90d29532c5d96fd064b3`) there is about +/- 3 min  of run-to-run variability.
In most cases `Prerelease` and `BuildMetadata` are empty. `Prerelease` already did not do …

Faster Ord when Eq

---

build.rs
src/lib.rs
src/parse.rs
tests/test_version_req.rs

Delete no_const_vec_new configuration

---

build.rs
src/display.rs
src/eval.rs
src/lib.rs

Delete no_non_exhaustive configuration
