dtolnay/semver

src/version_req.rs

* replaces unimplemented! with an Err
* removes unreachable error

Improve error handling

---

src/version.rs

This fixes the latest build, e.g. https://travis-ci.org/rust-lang/semver/builds/51544477#L102

Fix closure syntax

---

src/version_req.rs

r? @alexcrichton 
This will be particularly useful for cargo crates with "lose" dependencies on other crates (e.g. rust-postgres's dependency on rust-openssl).

Implement multiple version reqs

---

src/parser.rs

deal with hyphens correctly

---

.travis.yml
Cargo.toml
tests/regression.rs

This needs https://github.com/frewsxcv/rust-crates-index/pull/9 and a new release before it can be merged, I'll need to push another commit.

Regression test against crates.io

---

src/version.rs
src/version_req.rs

This lets you use `str::parse()`, eg,
let v: Version = "1.0".parse().unwrap();

Implement str::FromStr for Version and VersionReq

---

Cargo.toml
src/lib.rs
src/version.rs
src/version_req.rs

I need to fix up the errors before this can be merged, but let's check CI.

Final semver parser fix

---

.travis.yml
Cargo.toml

Move documentation to docs.rs

---

Cargo.toml

So that it gets rendered by crates.io

Add readme link to Cargo.toml

---

src/version_req.rs

Hey,
I recently started using VersionReq to perform artifact lookup, and I needed to build a cache of what a given package + version requirement resolved into.
Because VersionReq doesn't implement `Eq`, or `Hash`, this was not entirely straight forward.
This is not a perfect solution, I realize that there might be multiple version requirements which are semantically equivalent (like `1.*` vs `1.*.*`) and that the naive Hash and Eq implementation does not take this into account. But for my purposes, this is good enough.
An alternative would be to expose functions that permit implementing these in newtypes, preferably without having to resort to some hack like converting to string during comparisons.
If there are other alternatives, I would love to know!

Implement Hash, Eq, and Ord for VersionReq

---

.travis.yml
src/version.rs
src/version_req.rs
tests/deprecation.rs
tests/regression.rs
tests/serde.rs

Format all files and introduce a Travis build step that verifies formatting.

rustfmt all the things

---

README.md

Updated at line#10 from http://semver.org/ to https://semver.org/

Replaced HTTP by HTTPS

---

src/version.rs

Version display respect formatter settings

---

Cargo.toml

Keywords and Categories

---

src/lib.rs
src/version_req.rs

Thanks to @muzikmoe 
Resolves #132

Rebase #145 without formatting

---

README.md
src/lib.rs
src/version_req.rs

The NPM link returned 404, this fixes #193

Update NPM link

---

README.md

Update README to reflect latest published version

---

fuzz/parse_version.rs
fuzz/parse_version_req.rs

Seems like we can easily fuzz display as well, so why not?

Extend fuzzing to cover Display as well

---

.github/workflows/ci.yml
src/impls.rs

Fix FromIterator impl on no-std

---

src/display.rs
tests/test_version.rs

Support padding in displaying Version

---

src/error.rs
src/parse.rs
tests/test_version_req.rs

Improve error on comma after wildcard

---

tests/node/mod.rs
tests/test_version_req.rs

Add test that VersionReq::default() == VersionReq::STAR

---

src/identifier.rs
tests/test_autotrait.rs

Impl Send + Sync for Identifier

---

Cargo.toml
src/lib.rs

Only do rustdoc workaround for semver's own docs.rs build

---

src/backport.rs
src/identifier.rs

Check allocations for OOM

---

Cargo.toml

Enabled 'serde' feature on playground

---

build.rs
src/backport.rs
src/lib.rs

Delete no_alloc_crate configuration

---

build.rs
src/identifier.rs

Delete no_nonzero_bitscan configuration

---

src/backport.rs
src/impls.rs
src/lib.rs
src/parse.rs

Delete backport module
